## Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
import warnings
warnings.filterwarnings('ignore')
from pathlib import Path
import joblib

## Data Collection and Preprocessing

In [2]:
# Load the dataset using Pandas Dataframe
data_path=Path("../data/diabetes.csv")
d=pd.read_csv(data_path)

In [3]:
# Print first 5 rows of the dataset
d.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# Print the last 5 rows of the dataset
d.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
# Getting the rows and columns
d.shape

(768, 9)

There are 768 records and 9 columns

In [6]:
# Printing the column names
d.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [7]:
# Statistical measures of the dataset
d.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
# Printing the information about the dataset
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [9]:
# Checking the missing values
d.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

No Missing values found in the dataset.

In [10]:
# Target Column distribution
d['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0-> No Diabetes
1-> Diabetes exist

In [11]:
cols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

for c in cols:
    d[c] = d[c].replace(0, d[c].median())

## Train Test Split

In [12]:
# Creating the independent and dependent variable
X=d.drop(columns=['Outcome'])
y=d['Outcome']

In [13]:
# Splitting into test(20%) and train(80%) Data
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [14]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

## Logistic Regression

In [15]:
# Training with the logistic Model
lm=LogisticRegression(class_weight='balanced')
lm.fit(X_train,y_train)

LogisticRegression(class_weight='balanced')

In [16]:
# Predicting the testing data
lm_pred=lm.predict(X_test)

In [17]:
# Getting the Accuracy Score
accuracy_score(y_test,lm_pred)

0.6883116883116883

In [18]:
# Printing the Classification Report
print(classification_report(y_test, lm_pred))

              precision    recall  f1-score   support

           0       0.80      0.69      0.74        99
           1       0.55      0.69      0.61        55

    accuracy                           0.69       154
   macro avg       0.68      0.69      0.68       154
weighted avg       0.71      0.69      0.69       154

In [19]:
# Printing the Confusion Matrix
confusion_matrix(y_test, lm_pred)

array([[68, 31],
       [17, 38]])

## Random Forest

In [20]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [21]:
rf_pred=rf.predict(X_test)

In [22]:
accuracy_score(y_test,rf_pred)

0.7337662337662337

In [23]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.80      0.78      0.79        99
           1       0.62      0.65      0.64        55

    accuracy                           0.73       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.74      0.73      0.74       154

## SVM

In [24]:
sm=SVC()
sm.fit(X_train,y_train)

SVC()

In [25]:
sm_pred=sm.predict(X_test)

In [26]:
accuracy_score(y_test,sm_pred)

0.7532467532467533

In [27]:
print(classification_report(y_test, sm_pred))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82        99
           1       0.68      0.58      0.63        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.72       154
weighted avg       0.75      0.75      0.75       154

## XGBoost

In [28]:
xm=XGBClassifier(n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42)
xm.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [29]:
xm_pred=xm.predict(X_test)

In [30]:
accuracy_score(y_test,xm_pred)

0.7402597402597403

In [31]:
print(classification_report(y_test, xm_pred))

              precision    recall  f1-score   support

           0       0.82      0.77      0.79        99
           1       0.62      0.69      0.66        55

    accuracy                           0.74       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.74      0.74       154

## Model Selection

SVM was selected as the final model because it achieved a higher recall for the diabetic class, reducing false negatives and ensuring better detection of potential diabetes cases. In healthcare applications, recall is prioritized to avoid missing patients who may have the disease.

In [32]:
# Save the trained Model
joblib.dump(sm,"diabetes_model.pkl")

['diabetes_model.pkl']

## Predictive Model

In [33]:
sample = [[6,148,72,35,0,33.6,0.627,50]]

prediction = sm.predict(sample)

if prediction[0] == 1:
    print("Diabetic")
else:
    print("Not Diabetic")

Not Diabetic